export type Icon =
  | 'account_tree'
  | 'arrow_drop_down'
  | 'arrow_drop_up'
  | 'article'
  | 'chevron_right'
  | 'developer_board'
  | 'docs'
  | 'draft'
  | 'expand_more'
  | 'forms_add_on'
  | 'looks_one'
  | 'looks_two'
  | 'save'
  | 'settings'
  | 'usb'
  | 'usb_off';
